FILES=main.cpp Account.cpp Customer.cpp Bank.cpp TestApp.cpp Menu.cpp MenuItem.cpp Functions.cpp
FLAGS=-std=c++11 -Wall -pedantic
OUTFILE=main

all:
	g++ ${FILES} -o ${OUTFILE} ${FLAGS};

run:
	/.${OUTFILE}
