projectdir=~/Projects/Cpp-Obj/Project
FILES=main.cpp TestApp.cpp ${projectdir}/Functions.cpp ${projectdir}/Menu.cpp ${projectdir}/MenuItem.cpp
FLAGS=-std=c++11 -Wall -pedantic
all:
	g++ ${FILES} -o main ${FLAGS}